import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalNavbar } from "@/components/ui/skiper-ui/skiper13";
import { myFont, myFont1, myFont2, myFont3, myFont4, myFont5, myFont6, myFont7 } from "./fonts";
import PageFooter from "@/components/FooterPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sury.me",
  description: "Generated by create next app",
  icons: "./gg6.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${myFont1.variable} ${myFont3.variable} ${myFont4.variable} ${myFont5.variable} ${myFont6.variable} ${myFont7.variable} ${myFont2.variable} ${myFont.variable}`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  var shouldBeDark = theme === 'dark' || (!theme && prefersDark);
                  if (shouldBeDark) {
                    document.documentElement.classList.add('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
        <GlobalNavbar />
        {children}
        <PageFooter/>
      </body>
    </html>
  );
}
